[gcp_service_account]
type = "service_account"
project_id = "esoteric-bruin-466701-n3"
private_key_id = "7e7cb710306e757374cd8d4888b0274db6199674"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC6Tmk9gHCfPYSc
gUYajFUyfgB73f78H4ahjmBaw2BOcYL9hHkvrW6MQeQLVwAYrhUG5wNHjAe3KVGW
qr1SKHn4JUZi/6sdSvucOnlPvkp1mLW9OV+4pDBijWyRfGxEXzPIH2t0L2QyuUn9
Kn20KXO1I83Zpc3HgYho3a2zu/7N9KtTQjmVRPdZXYNbFMdvJmbMf3EMUJxV62LK
9jG40IRJc3/EjQpJjbzmra72xEonQ9b/eujKwsGHBW3eYmNFndGF3rQZsHIMiypZ
zbIN9AtlTt7Z7vLtKCSA4KZ7s3v01f53d9gQhHpu7pXyRbaIJoVB5BKq3MUUU+6z
SZuxFgAXAgMBAAECggEAIeJj+qcTFKs8JLjQVsDCOBI5pU2tdA6JznVWKfvR1sKH
Z/OBlP3OltzfDH7wygxTT7ORYaBiwNnXeHcqQriQ4mRpJlVIumWqWHI8IRhDc5ro
Jve55JucHziIj/dYu6CzCslIIlQCPcV8Yvqo7S0C2eWeqWCiChCRjj0PPBrLj4qK
K38cMq48IN5b0uPnI4jeBWT1k/RnVJcnT01GQO39Tw7b2QtdiIcFCbOhq9HWUYLK
G36ejab4SSMLeaZODPd20SGCVOkLcKAWzFaIXS4hSaIwGE8oPg29yqEVFM6HNoCI
eW4D5jwoIGpFWzaZyerotewBqh1tBwJzmBC8kvX/oQKBgQDtlZcE8t5vNKBztiJ3
VnxOD/8/W94D2ejiFJYmdSAXN6sAdnDM5HD9vgYUWEi2Mx85w6+WkIjg2pbkJ5iC
6YyLNglQjnrW9win4pvwi3Dm6kkim7pTj3eFmC6DktXMLVAeA0j1JrLcXpFXKWVq
KqE5+gyMSi6pThuqAN8+OomLIQKBgQDIv05HhzuoAMZeEFFnSxUgy6SLkvWlCcAT
RnRfBZ092bD7Rlo2Es9JerScfRiNqgAs249P8ewAerRZDYIjNoZPSZDdsAN7EXtv
OTFVLxVZxWYyOq2HS8cyYupvVCHuQauicwjKBAJihuk37EhYd6pJQTCiAXgDu1IJ
/PIcLaGcNwKBgBCv0AKV+E+BN7/IzBTrqyFkeD3/+tD0binq3jznPxDCZS1MJFIP
vWvk+9JT/Q9m+ct51gxSLHr2f2CY81pGgwuICRFyYGhWw3HfNaqocI6XZ/mZTHXv
/qoQbTvqhT+o8xaYjnhBdpCJx9WCX9AcHGTRDi6QS0Sy6rh/BS7+t4hhAoGAeaYE
J7A5ZGtjyeiVi8Sh/weopLPfi61G6edN6a8bRDnA1+QgEph/aIWlIRdlY6NbC9PZ
Gpb9bqTs2PIopHIMHcv0r4JT+aX0aMf9ryMjCw1mCpYoRc6T3WK3sdMH5LuC6KRQ
9SpMz6v1c+AJTyLk3BNXBzVgptJCuq6/gHfecS0CgYByWRC/JrCM/cIiu5dcPQml
rfIO4rAhV76CvfyX76WXJaqHyznYo/lBGvNYhqsUrTqIOKyFVHsV+ctW78Sj/TGj
O96jGEETSoIWsBJNQ9A0kx3FdU450iwv+2A1R1K2iqLtfTHh/6MSIg3VDaJZPo3h
4wBMOitOS0ZXG8V5vDdK6g==
-----END PRIVATE KEY-----"""
client_email = "streamlit-service@esoteric-bruin-466701-n3.iam.gserviceaccount.com"
token_uri = "https://oauth2.googleapis.com/token"
